import React from "react";
import { AlertTriangle, CheckCircle, AlertOctagon, FileText, Download, Printer } from "lucide-react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell, LabelList } from "recharts";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { ScreeningLabel } from "../types";

const ResultPanel = ({ result, patient, cbcRows }) => {
  const loadImage = (url) => {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.src = url;
      img.onload = () => resolve(img);
      img.onerror = reject;
    });
  };

  const generateDoc = async () => {
    const doc = new jsPDF();

    doc.setFillColor(13, 148, 136);
    doc.rect(0, 0, 210, 20, "F");

    // Add Logo
    try {
      const logo = await loadImage("/logo.png");
      doc.addImage(logo, "PNG", 10, 2, 16, 16);

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(16);
      doc.text("Clinomic Labs", 30, 13); // Shifted right
    } catch (e) {
      console.error("Could not load logo", e);
      // Fallback if logo fails
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(16);
      doc.text("Clinomic Labs", 14, 13);
    }

    doc.setFontSize(10);
    doc.text("Vitamin B12 Screening Report", 195, 13, { align: "right" });

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    doc.text(`Patient Name: ${patient.name || "N/A"}`, 14, 30);
    doc.text(`Patient ID: ${patient.id}`, 14, 36);
    doc.text(`Age/Sex: ${patient.age || "-"} / ${patient.sex}`, 14, 42);

    doc.text(`Date: ${patient.date}`, 140, 30);
    doc.text(`Lab Ref: ${patient.labId}`, 140, 36);

    doc.setDrawColor(200, 200, 200);
    doc.line(14, 48, 196, 48);

    const pNormalVal = result.probabilities.normal;
    const pBorderVal = result.probabilities.borderline;
    const pDeficientVal = result.probabilities.deficient;

    let labelText = "Normal";
    let color = [34, 197, 94];

    if (pDeficientVal > Math.max(pNormalVal, pBorderVal)) {
      labelText = "Deficient";
      color = [239, 68, 68];
    } else if (pBorderVal > Math.max(pNormalVal, pDeficientVal)) {
      labelText = "Borderline";
      color = [245, 158, 11];
    }

    doc.setFontSize(14);
    doc.setTextColor(color[0], color[1], color[2]);
    doc.text(`Screening Result: ${labelText}`, 14, 58);

    doc.setTextColor(60, 60, 60);
    doc.setFontSize(10);
    const maxProb = Math.max(pNormalVal, pBorderVal, pDeficientVal);
    doc.text(`Model Confidence: ${(maxProb * 100).toFixed(1)}%`, 14, 66);

    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.rect(14, 74, 182, 30, "FD");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text("Clinical Interpretation:", 16, 80);
    doc.setFont("helvetica", "italic");
    doc.text(result.interpretation || "", 16, 86, { maxWidth: 178 });

    doc.setFont("helvetica", "bold");
    doc.text("Recommendation:", 16, 94);
    doc.setFont("helvetica", "normal");
    doc.text(result.recommendation || "", 16, 100, { maxWidth: 178 });

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("Hematological Indices", 14, 114);

    const indicesBody = [
      ["Mentzer Index", String(result.indices.mentzer), result.indices.mentzer > 13 ? "Possible Iron Deficiency" : "Possible Thalassemia"],
      ["Green & King Index", String(result.indices.greenKing), "Differentiation of IDA vs Thalassemia"],
      ["NLR (Neutrophil/Lymphocyte)", String(result.indices.nlr), "Inflammatory Marker"],
    ];

    autoTable(doc, {
      startY: 118,
      head: [["Index", "Value", "Clinical Significance"]],
      body: indicesBody,
      theme: "grid",
      headStyles: { fillColor: [15, 118, 110], fontSize: 9 },
      styles: { fontSize: 8, cellPadding: 2 },
      columnStyles: { 0: { fontStyle: "bold" } },
    });

    const finalY = doc.lastAutoTable.finalY + 12;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("Complete Blood Count (CBC) Data", 14, finalY);

    const cbcBody = cbcRows.map((row) => [
      row.test,
      row.value || "-",
      row.unit,
      `${(patient.sex === "M" ? row.refRangeM : row.refRangeF).join(" - ")}`,
    ]);

    autoTable(doc, {
      startY: finalY + 4,
      head: [["Test", "Result", "Unit", "Ref. Range"]],
      body: cbcBody,
      theme: "striped",
      headStyles: { fillColor: [71, 85, 105], fontSize: 9 },
      styles: { fontSize: 8, cellPadding: 2 },
      alternateRowStyles: { fillColor: [241, 245, 249] },
    });

    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i += 1) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(`Page ${i} of ${pageCount}`, 195, 290, { align: "right" });
      doc.text("Generated by Clinomic Labs LIS - For Investigational Use Only", 105, 290, { align: "center" });
    }

    return doc;
  };

  const handleDownloadPDF = async () => {
    const doc = await generateDoc();
    doc.save(`ClinomicLabs_Report_${patient.id}.pdf`);
  };

  const handlePrint = async () => {
    const doc = await generateDoc();
    doc.autoPrint();
    const blob = doc.output("blob");
    const url = URL.createObjectURL(blob);
    window.open(url, "_blank");
  };

  const getBadge = (label) => {
    const pNormal = (result.probabilities.normal * 100).toFixed(1);
    const pBorder = (result.probabilities.borderline * 100).toFixed(1);
    const pDeficient = (result.probabilities.deficient * 100).toFixed(1);

    const breakdown = (
      <div className="mt-1 text-xs font-medium opacity-90">
        N: {pNormal}% | B: {pBorder}% | D: {pDeficient}%
      </div>
    );

    switch (label) {
      case ScreeningLabel.NORMAL:
        return (
          <div className="flex items-center space-x-2 bg-green-50 border border-green-200 text-green-800 px-4 py-3 rounded-md shadow-sm" data-testid="result-badge-normal">
            <CheckCircle className="w-6 h-6 text-green-600" />
            <div>
              <p className="text-xs font-bold uppercase tracking-wider text-green-600">Screening Result</p>
              <h3 className="text-xl font-bold">Low Risk (Normal)</h3>
              {breakdown}
            </div>
          </div>
        );
      case ScreeningLabel.BORDERLINE:
        return (
          <div className="flex items-center space-x-2 bg-amber-50 border border-amber-200 text-amber-800 px-4 py-3 rounded-md shadow-sm" data-testid="result-badge-borderline">
            <AlertTriangle className="w-6 h-6 text-amber-600" />
            <div>
              <p className="text-xs font-bold uppercase tracking-wider text-amber-600">Screening Result</p>
              <h3 className="text-xl font-bold">Borderline / Indeterminate</h3>
              {breakdown}
            </div>
          </div>
        );
      case ScreeningLabel.DEFICIENT:
      default:
        return (
          <div className="flex items-center space-x-2 bg-red-50 border border-red-200 text-red-800 px-4 py-3 rounded-md shadow-sm" data-testid="result-badge-deficient">
            <AlertOctagon className="w-6 h-6 text-red-600" />
            <div>
              <p className="text-xs font-bold uppercase tracking-wider text-red-600">Screening Result</p>
              <h3 className="text-xl font-bold">High Risk (Deficiency)</h3>
              {breakdown}
            </div>
          </div>
        );
    }
  };

  const chartData = [
    { name: "Normal", value: parseFloat((result.probabilities.normal * 100).toFixed(1)) },
    { name: "Borderline", value: parseFloat((result.probabilities.borderline * 100).toFixed(1)) },
    { name: "Deficient", value: parseFloat((result.probabilities.deficient * 100).toFixed(1)) },
  ];

  const getBarColor = (index) => {
    if (index === 0) return "#22c55e";
    if (index === 1) return "#f59e0b";
    return "#ef4444";
  };

  return (
    <div data-testid="result-panel" className="bg-white border border-slate-300 shadow-sm rounded-sm p-5 space-y-6">
      <div className="flex justify-between items-start">
        <h2 className="text-lg font-bold text-slate-800 flex items-center">
          <FileText className="w-5 h-5 mr-2 text-teal-600" />
          Screening Analysis Report
        </h2>
        <div className="flex space-x-2">
          <button
            data-testid="print-report-button"
            onClick={handlePrint}
            className="flex items-center px-3 py-1.5 text-xs font-medium text-slate-600 bg-slate-100 hover:bg-slate-200 rounded border border-slate-200"
          >
            <Printer className="w-3.5 h-3.5 mr-1.5" /> Print
          </button>
          <button
            data-testid="download-pdf-button"
            onClick={handleDownloadPDF}
            className="flex items-center px-3 py-1.5 text-xs font-medium text-slate-600 bg-slate-100 hover:bg-slate-200 rounded border border-slate-200"
          >
            <Download className="w-3.5 h-3.5 mr-1.5" /> PDF
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="space-y-4">
          {getBadge(result.label)}

          <div className="bg-slate-50 p-4 rounded border border-slate-200">
            <h4 className="text-sm font-semibold text-slate-700 mb-2 border-b border-slate-200 pb-2">Clinical Interpretation</h4>
            <p className="text-sm text-slate-800 leading-relaxed italic">"{result.interpretation}"</p>
          </div>

          <div className="bg-blue-50 p-4 rounded border border-blue-100">
            <h4 className="text-sm font-semibold text-blue-800 mb-2 border-b border-blue-200 pb-2">Recommendation</h4>
            <p className="text-sm text-blue-900 font-medium">{result.recommendation}</p>
          </div>
        </div>

        <div className="border border-slate-200 rounded p-4 bg-white">
          <h4 className="text-xs font-semibold text-slate-500 uppercase mb-4 text-center">Model Confidence Probabilities</h4>
          <div className="h-48 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chartData} layout="vertical" margin={{ top: 5, right: 30, left: 40, bottom: 5 }}>
                <XAxis type="number" domain={[0, 100]} hide />
                <YAxis dataKey="name" type="category" tick={{ fontSize: 12 }} width={80} />
                <Tooltip cursor={{ fill: "transparent" }} contentStyle={{ fontSize: "12px" }} />
                <Bar dataKey="value" barSize={24} radius={[0, 4, 4, 0]} background={{ fill: "#f1f5f9" }}>
                  <LabelList dataKey="value" position="right" formatter={(val) => `${val}%`} />
                  {chartData.map((entry, index) => (
                    <Cell key={`cell-${entry.name}`} fill={getBarColor(index)} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      <div>
        <h4 className="text-sm font-bold text-slate-700 mb-3">Calculated Hematological Indices</h4>
        <div className="overflow-hidden border border-slate-200 rounded-sm">
          <table className="min-w-full divide-y divide-slate-200 text-sm">
            <thead className="bg-slate-50">
              <tr>
                <th className="px-4 py-2 text-left font-medium text-slate-600">Index</th>
                <th className="px-4 py-2 text-right font-medium text-slate-600">Value</th>
                <th className="px-4 py-2 text-left font-medium text-slate-600">Clinical Significance</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 bg-white">
              <tr>
                <td className="px-4 py-2 font-medium text-slate-800">Mentzer Index</td>
                <td className="px-4 py-2 text-right font-mono">{result.indices.mentzer}</td>
                <td className="px-4 py-2 text-slate-500 text-xs">{result.indices.mentzer > 13 ? "Suggests Iron Deficiency" : "Suggests Thalassemia Trait"} (if microcytic)</td>
              </tr>
              <tr>
                <td className="px-4 py-2 font-medium text-slate-800">Green & King Index</td>
                <td className="px-4 py-2 text-right font-mono">{result.indices.greenKing}</td>
                <td className="px-4 py-2 text-slate-500 text-xs">Used for differentiating IDA vs Thalassemia</td>
              </tr>
              <tr>
                <td className="px-4 py-2 font-medium text-slate-800">NLR (Neutrophil/Lymphocyte)</td>
                <td className="px-4 py-2 text-right font-mono">{result.indices.nlr}</td>
                <td className="px-4 py-2 text-slate-500 text-xs">Inflammatory marker</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default ResultPanel;
